# Generated by Django 4.0.4 on 2022-05-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.CharField(default='abc@gmail.com', max_length=40),
        ),
    ]
